### ISSUE TITLE
Feature request: add copy paste

### ISSUE THREAD

**Issue by arelaxend** [ugogo/react-input-verification-code#2]
Hello / bonjour,

One may look for the feature copy/paste of codes.

**Expected workflow:**
- a user copies a code
- a user pastes the code in a browser tab where there is a `react-input-verification-code`
- this triggers the `onChange` callback

**Additional resources:**
- https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event

A.

**Comment by ugogo** [comment]
Hi, @arelaxend,
Thanks for the suggestion, I'll have a look 👀

**Comment by ugogo** [comment]
👋 @arelaxend (sorry for the double ping)
It's live in the [0.5.0 version](https://github.com/ugogo/react-input-verification-code/releases/tag/0.5.0)

Feel free to re-open the issue it if needed
Cheers
