### ISSUE TITLE
how to clear the entered value ?

### ISSUE THREAD

**Issue by mehrzad7394** [ugogo/react-input-verification-code#3]
hi,am planning to clear the entered code with the button ,can u plz guide me  that how it can be done?!
thanks

**Comment by ugogo** [comment]
Hi @mehrzad7394 , sorry for the delay!
Since the `0.6.4` version, you can pass a `value` to the component.
You can find an example here https://codesandbox.io/s/controllable-32dfy

Cheers :v:

**Comment by mehrzad7394** [comment]
> Hi @mehrzad7394, sorry for the delay!
> Since the `0.6.4` version, you can pass a `value` prop to the component.
> You can find an example here https://codesandbox.io/s/controllable-32dfy
> 
> Cheers
.
hi @ugogo ,thanks for the great help.one more thing which i was stuck with is,how can i set the focus on the first box?
i mean to say soon as the page is loaded i want the focus on the first value to type it automatically without clicking on it.

**Comment by ugogo** [comment]
This is not supported at the moment, would you be willing to open a PR for this?

**Comment by ugogo** [comment]
Closing this for now as this is not related to the main concern.
Feel free to open a PR/issue.
