### ISSUE TITLE
More documentation around how to style 

### ISSUE THREAD

**Issue by dkoleary88** [ugogo/react-input-verification-code#4]
I just spent a ton of time trying to figure out how to style this thing. A lot more than I would've imagined for something so simple.
It'd be nice if we had clearer and more detailed documentation on styling.

**Comment by ugogo** [comment]
Hi @dkoleary88,

What issue did you run into?
Have you looked at the example listed in the README? (Here is the CodeSandbox link as a reference: https://codesandbox.io/s/custom-styles-bw8s4?file=/src/index.css)

**Comment by ugogo** [comment]
Closing this, feel free to reopen if needed
