### ISSUE TITLE
onCompleted is triggered when placeholder is just one digit/character

### ISSUE THREAD

**Issue by n3m** [ugogo/react-input-verification-code#43]
While playing a little bit with the lib, I found out that using a 1 digit/character placeholder, the onCompleted method is triggered.

I was trying to use this lib in a Dialog that closes when the onCompleted trigger is hit, so this bug actually breaks that functionality.

EDIT: Solution was just to ignore the value of the placeholder because the placeholder value was being constructed into a state that would trigger the onCompleted function

**Comment by ugogo** [comment]
Thanks for the fix @n3m, it has been released in the [v1.0.1 ](https://github.com/ugogo/react-input-verification-code/releases/tag/1.0.1)
