### ISSUE TITLE
Can't paste on mobile

### ISSUE THREAD

**Issue by henryoliver** [ugogo/react-input-verification-code#46]
Hi there, thanks for creating this library!

I'm running into this issue of not being able to trigger the `paste` functionality by touching and holding in any of the fields. If the user touches holding the finger in any other input or text it will popup the <copy, paste, select...> tooltip, but for some reason, it does not work on this library.

You can access the link below to do a quick test o your mobile phone:
https://codesandbox.io/s/basic-6ejdp

Looking for solutions before moving on.

Thanks!
Henry

**Comment by ugogo** [comment]
Hey @henryoliver,

Thanks for the bug report.
I'll try to have a look at it shortly

🙏

**Comment by ugogo** [comment]
Hey, sorry for the delay 👋 

I tried with the `v2` and everything seems to work as expected
Please upgrade and feel free to reopen if the issue still occurs
