### ISSUE TITLE
Support of autofocus attribute

### ISSUE THREAD

**Issue by spacehill** [ugogo/react-input-verification-code#5]
Hello,

It would be cool if the component is capable of of autofocusing

Expected behavior:

on mount, if "autoFocus" is set, the component will focus to the first digit field.

**Comment by ugogo** [comment]
Hello @spacehill 
Yes, that's something I tried to do in the beginning, but on some mobile devices the keyboard was not opening for some reasons
If you have a lead, please open a pull-request 🙂

**Comment by ugogo** [comment]
Done in `0.7.0`
