### ISSUE TITLE
Allow all kinds of input characters

### ISSUE THREAD

**Issue by silicakes** [ugogo/react-input-verification-code#54]
Hi,
I'd like to use this library to input various characters and not be limited by numbers alone.
Removing the regex tests (which should be handled in the application level IMO) solves the problem for me.

Is there a reason keeping it in the code?

**Comment by GilAkivaWebiya** [comment]
@ugogo @silicakes 
Hi, i solved the problem i add a PR a support 2 ways 
1. only numbers
2. numbers and letters (you can write only letters if you want)

i add a new props:
inputMode: "text" | "numeric" the default is numeric 

please approve this PR to fix the problem 

link to PR:  https://github.com/ugogo/react-input-verification-code/pull/56

**Comment by ugogo** [comment]
Hello there 👋 

Thanks for your contributions, I'm currently on holidays and will have a deeper look at this as soon as I get back

**Comment by ugogo** [comment]
Hey, me again 👋 

I'm close to release a v2 with a complete code refactor
The feature you're requesting will be included 

Thanks for your patience 🙏

**Comment by ugogo** [comment]
Hello 👋 

The **pre-release** of the `v2.0.0-0` has been released
https://github.com/ugogo/react-input-verification-code/releases

You can now use `type: 'alphanumeric'` to allow letters and numbers
https://github.com/ugogo/react-input-verification-code/blob/2.0.0-1/README.md

I'll do a QA in the coming week and publish the v2.0.0 if everything's working as expected
Feel free to share any feedbacks or issues 🙂
