### ISSUE TITLE
Can not find module styled-component when run build

### ISSUE THREAD

**Issue by NguyenKyThinh94** [ugogo/react-input-verification-code#72]
Version `1.0.2`
We use gatsby framework.
I run `npm install` everithing is good.
But i run gatsby build, `react-input-verification-code` report can not find `styled-component`
Note: I up vertion to `2.0.0-9` it work good.

**Comment by ugogo** [comment]
👋 @NguyenKyThinh94 

`styled-components` is listed as a peer `peerDependencies`, meaning that you have to install it by yourself

https://github.com/ugogo/react-input-verification-code/blob/1.0.2/package.json#L45

Feel free to reopen the issue if needed
Have a nice day 🌻
